apiVersion: apps/v1
kind: Deployment
metadata:  
  annotations:    
    deployment.kubernetes.io/revision: "1"
  generation: 1   
  labels:        
    app: webhook-server 
  name: webhook-server                      
  namespace: webhook
spec:                                                                                                                                                                                                                                          
  progressDeadlineSeconds: 600                                                                                                                                                                                                                 
  replicas: 1                                                                                                                                                                                                                                  
  revisionHistoryLimit: 3                                                                                                                                                                                                                      
  selector:                                                                                                                                                                                                                                    
    matchLabels:                                                                                                                                                                                                                               
      app: webhook-server                                                                                                                                                                                                                               
  strategy:                                                                                                                                                                                                                                    
    rollingUpdate:                                                                                                                                                                                                                             
      maxSurge: 25%                                                                                                                                                                                                                            
      maxUnavailable: 25%                                                                                                                                                                                                                      
    type: RollingUpdate                                                                                                                                                                                                                        
  template:                                                                                                                                                                                                                                    
    metadata:                                                                                                                                                                                                                                  
      creationTimestamp: null
      labels:
        app: webhook-server
        name: webhook-server
    spec:
      affinity: {}
      containers:
      - image: <webhook-server-image>
        imagePullPolicy: IfNotPresent
        name: webhook-server
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        volumeMounts:
        - name: webhook-certs
          mountPath: "/etc/webhook/certs"
          readOnly: true
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 1G
            memory: 2G
          requests:
            cpu: "1"
            ephemeral-storage: 1G
            memory: 2G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-server-tls
