apiVersion: v1
kind: Service
metadata:
  name: webhook-server-service
  namespace: webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: webhook-server
