apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-validation
  namespace: webhook
webhooks:
  - name: webhook-server.webhook.svc
    clientConfig:
      service:
        name: webhook-server-service
        namespace: webhook
        path: "/validate"
      caBundle: <base64-encoded-certificate>
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]